[package]
name = "output"
version = "0.1.0"
authors = ["Pascal Hertleif <killercup@gmail.com>"]

[dependencies]
termcolor = "1.0.4"
serde = "1.0.79"
serde_json = "1.0.31"
failure_derive = "0.1.2"
failure = "0.1.2"
serde_derive = "1.0.79"
